### ISSUE TITLE
Tic-Tac-Toe with Python

### ISSUE THREAD

**Issue by mahadihassanriyadh** [BUHPHSS/Python-Projects#12]
I would like to build a Tic-Tac-Toe game with python.

**Comment by mahadihassanriyadh** [comment]
Please assign me to the issue if this is eligible for [Hacktoberfest 2022](https://hacktoberfest.com/).

**Comment by mitul3737** [comment]
@mahadihassanriyadh please proceed

**Comment by mahadihassanriyadh** [comment]
@mitul3737 Will you assign me, please?

**Comment by 0xYashwanth** [comment]
Hey, I have a pretty decent knowledge of python. I want to contribute to the leap-year program. Could you please assign this to me?
Thanks for reading.

**Comment by mitul3737** [comment]
@0xYashwanth You can proceed
